#!/usr/bin/env python3
"""
train_model.py — Phase 3: Train and compare classifiers for shock/handling.

Trains three candidates:
  (a) Decision Tree / Random Forest  -> exported to plain C array
  (b) Small MLP on features          -> TFLite int8
  (c) 1D-CNN on raw windows          -> TFLite int8

Evaluates on the held-out test split and selects the best model within
the ESP32 hardware budget:
  - Tensor arena: <= 24 KB
  - Model flash:  <= 60 KB
  - Classes:      0=normal, 1=shock, 2=drop, 3=rough_handling

Usage:
  python train_model.py --dataset dataset/ --output models/
  python train_model.py --dataset dataset/ --output models/ --skip_cnn

Pinned random seeds everywhere. All numbers reported are on the synthetic
test split only; NOT real-world accuracy.
"""

import argparse
import json
import os
import sys
import time
import struct
from pathlib import Path

import numpy as np

# ────────────────────────────────────────────────────────────
# Lazy imports with helpful error messages
# ────────────────────────────────────────────────────────────
def _require(pkg, install_hint):
    try:
        return __import__(pkg)
    except ImportError:
        print(f"[ERROR] Missing '{pkg}'. Install: {install_hint}")
        sys.exit(1)

SEED = 42
CLASS_NAMES = ["normal", "shock", "drop", "rough_handling"]
NUM_FEATURES = 16
WINDOW_SAMPLES = 125

# Hardware budgets
MAX_ARENA_BYTES = 24 * 1024   # 24 KB
MAX_MODEL_BYTES = 60 * 1024   # 60 KB

# ────────────────────────────────────────────────────────────
# Feature loading
# ────────────────────────────────────────────────────────────

def load_features(dataset_dir):
    """Load raw windows and extract features for train/val/test."""
    from features import extract_features_batch

    d = Path(dataset_dir)
    result = {}
    for split in ["train", "val", "test"]:
        X = np.load(d / f"X_{split}.npy")   # (N, 125, 6) int16
        y = np.load(d / f"y_{split}.npy")   # (N,) int8
        print(f"  Extracting features: {split} ({len(y)} windows)...")
        Xf = extract_features_batch(X)       # (N, 16) float32
        result[split] = (Xf, y.astype(np.int64), X)
    return result


def load_scaler_stats(X_train_feat):
    """Compute min/max per feature on training set (for int8 quantisation)."""
    fmin = X_train_feat.min(axis=0)
    fmax = X_train_feat.max(axis=0)
    return fmin, fmax


def scale_features(X, fmin, fmax):
    """Scale features to [-1, 1] range using train set statistics."""
    denom = fmax - fmin
    denom[denom < 1e-6] = 1.0
    return 2.0 * (X - fmin) / denom - 1.0


# ────────────────────────────────────────────────────────────
# Model (a): Random Forest → C code
# ────────────────────────────────────────────────────────────

def train_random_forest(X_tr, y_tr, X_val, y_val):
    sklearn = _require("sklearn", "pip install scikit-learn")
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.metrics import classification_report, confusion_matrix

    print("\n[RF] Training Random Forest...")
    t0 = time.time()
    rf = RandomForestClassifier(
        n_estimators=20,
        max_depth=8,
        min_samples_leaf=4,
        random_state=SEED,
        n_jobs=-1,
    )
    rf.fit(X_tr, y_tr)
    t1 = time.time()
    print(f"  Train time: {t1-t0:.2f}s")

    y_pred_val = rf.predict(X_val)
    report = classification_report(y_val, y_pred_val, target_names=CLASS_NAMES, digits=3)
    cm = confusion_matrix(y_val, y_pred_val)
    print("[RF] Validation report:")
    print(report)
    print("[RF] Confusion matrix (val):")
    _print_cm(cm)

    return rf, report, cm


def rf_to_c_code(rf, fmin, fmax, output_path):
    """
    Export a sklearn RandomForestClassifier to a self-contained C header.
    Uses a recursive descent evaluator (no malloc, pure stack).
    Estimated flash: ~1–3 KB per tree * n_estimators.
    """
    from sklearn.tree import DecisionTreeClassifier

    lines = []
    lines += [
        "// Auto-generated by train_model.py — DO NOT EDIT",
        "// Random Forest classifier for cargo shock/handling (4 classes)",
        "#pragma once",
        "#include <stdint.h>",
        "#include <string.h>",
        "",
        f"#define RF_NUM_FEATURES  {rf.n_features_in_}",
        f"#define RF_NUM_CLASSES   {rf.n_classes_}",
        f"#define RF_NUM_TREES     {len(rf.estimators_)}",
        "",
        "// Feature scaling constants (train set min/max -> [-1, 1])",
        "static const float RF_FEAT_MIN[RF_NUM_FEATURES] = {",
        "  " + ", ".join(f"{v:.6f}f" for v in fmin),
        "};",
        "static const float RF_FEAT_MAX[RF_NUM_FEATURES] = {",
        "  " + ", ".join(f"{v:.6f}f" for v in fmax),
        "};",
        "",
    ]

    # Encode each tree as threshold/feature/left/right/value arrays
    all_tree_structs = []
    for ti, estimator in enumerate(rf.estimators_):
        t = estimator.tree_
        n = t.node_count
        lines += [f"// Tree {ti}: {n} nodes"]
        lines += [f"static const int8_t  RF_T{ti}_FEAT[{n}]  = {{",
                  "  " + ", ".join(str(int(v)) for v in t.feature) + "};"]
        lines += [f"static const float   RF_T{ti}_THR[{n}]   = {{",
                  "  " + ", ".join(f"{v:.6f}f" for v in t.threshold) + "};"]
        lines += [f"static const int16_t RF_T{ti}_LEFT[{n}]  = {{",
                  "  " + ", ".join(str(int(v)) for v in t.children_left) + "};"]
        lines += [f"static const int16_t RF_T{ti}_RIGHT[{n}] = {{",
                  "  " + ", ".join(str(int(v)) for v in t.children_right) + "};"]
        # Majority class per leaf: argmax of value[node, 0, :]
        leaf_class = np.argmax(t.value[:, 0, :], axis=1).astype(np.int8)
        lines += [f"static const int8_t  RF_T{ti}_CLASS[{n}] = {{",
                  "  " + ", ".join(str(v) for v in leaf_class) + "};"]
        lines += [""]
        all_tree_structs.append(ti)

    # Inference function
    lines += [
        "static inline int8_t _rf_predict_tree(",
        "    const int8_t *feat, const float *thr,",
        "    const int16_t *left, const int16_t *right,",
        "    const int8_t *cls_arr, const float *x_scaled)",
        "{",
        "  int16_t node = 0;",
        "  while (feat[node] >= 0) {",
        "    if (x_scaled[feat[node]] <= thr[node])",
        "      node = left[node];",
        "    else",
        "      node = right[node];",
        "  }",
        "  return cls_arr[node];",
        "}",
        "",
        "// Scale one feature vector in-place (fills x_out from x_raw)",
        "static inline void rf_scale_features(const float *x_raw, float *x_out) {",
        "  for (int i = 0; i < RF_NUM_FEATURES; i++) {",
        "    float denom = RF_FEAT_MAX[i] - RF_FEAT_MIN[i];",
        "    if (denom < 1e-6f) denom = 1.0f;",
        "    x_out[i] = 2.0f * (x_raw[i] - RF_FEAT_MIN[i]) / denom - 1.0f;",
        "  }",
        "}",
        "",
        "// Main inference: x_raw = 16 unscaled features, returns class 0-3",
        "// votes[] is optional output (NULL to skip); pass float[4]",
        "static inline int8_t rf_predict(const float *x_raw, float *votes) {",
        "  float x_scaled[RF_NUM_FEATURES];",
        "  rf_scale_features(x_raw, x_scaled);",
        "  int counts[RF_NUM_CLASSES] = {0};",
        "",
    ]
    for ti in all_tree_structs:
        lines += [
            f"  counts[_rf_predict_tree(RF_T{ti}_FEAT, RF_T{ti}_THR,",
            f"    RF_T{ti}_LEFT, RF_T{ti}_RIGHT, RF_T{ti}_CLASS, x_scaled)]++;",
        ]
    lines += [
        "  if (votes) {",
        "    for (int i=0;i<RF_NUM_CLASSES;i++)",
        f"      votes[i]=(float)counts[i]/{len(all_tree_structs)}.0f;",
        "  }",
        "  int best=0; for(int i=1;i<RF_NUM_CLASSES;i++) if(counts[i]>counts[best]) best=i;",
        "  return (int8_t)best;",
        "}",
    ]

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    size = os.path.getsize(output_path)
    print(f"  [RF] C header written: {output_path} ({size} bytes)")
    return size


# ────────────────────────────────────────────────────────────
# Model (b): Small MLP (feature-based) → TFLite int8
# ────────────────────────────────────────────────────────────

def train_mlp(X_tr, y_tr, X_val, y_val):
    """Train a tiny 2-layer MLP on the 16 features."""
    tf = _require("tensorflow", "pip install tensorflow>=2.13")
    from tensorflow import keras
    import tensorflow as tf2

    tf2.random.set_seed(SEED)
    np.random.seed(SEED)

    model = keras.Sequential([
        keras.layers.Input(shape=(NUM_FEATURES,)),
        keras.layers.Dense(32, activation="relu"),
        keras.layers.Dense(16, activation="relu"),
        keras.layers.Dense(4, activation="softmax"),
    ], name="mlp_cargo")

    model.compile(
        optimizer=keras.optimizers.Adam(1e-3),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )
    model.summary()

    cb = [
        keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True),
        keras.callbacks.ReduceLROnPlateau(factor=0.5, patience=5),
    ]
    history = model.fit(
        X_tr, y_tr,
        validation_data=(X_val, y_val),
        epochs=100, batch_size=256,
        callbacks=cb, verbose=1,
    )
    return model, history


def mlp_to_tflite_int8(model, X_repr, output_path):
    """Quantize MLP to int8 TFLite and save."""
    import tensorflow as tf

    def representative_dataset():
        idx = np.random.default_rng(0).integers(0, len(X_repr), 200)
        for i in idx:
            yield [X_repr[i:i+1]]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type  = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model = converter.convert()
    with open(output_path, "wb") as f:
        f.write(tflite_model)
    size = len(tflite_model)
    print(f"  [MLP] TFLite int8 model: {output_path} ({size} bytes)")
    return tflite_model, size


# ────────────────────────────────────────────────────────────
# Model (c): 1D-CNN on raw windows → TFLite int8
# ────────────────────────────────────────────────────────────

def train_cnn(X_tr_raw, y_tr, X_val_raw, y_val):
    """
    Small 1D-CNN on raw (125, 6) int16 windows, cast to float32 and scaled.
    Architecture designed to fit within 24 KB arena.
    """
    tf = _require("tensorflow", "pip install tensorflow>=2.13")
    from tensorflow import keras
    import tensorflow as tf2

    tf2.random.set_seed(SEED)

    # Normalise raw to float32 in [-1, 1] range
    def norm(X):
        X = X.astype(np.float32)
        X[:, :, :3] /= 32768.0   # accel
        X[:, :, 3:] /= 32768.0   # gyro (same range)
        return X

    X_tr  = norm(X_tr_raw)
    X_val_n = norm(X_val_raw)

    model = keras.Sequential([
        keras.layers.Input(shape=(WINDOW_SAMPLES, 6)),
        keras.layers.Conv1D(8, kernel_size=7, strides=2, activation="relu", padding="same"),
        keras.layers.Conv1D(16, kernel_size=5, strides=2, activation="relu", padding="same"),
        keras.layers.GlobalAveragePooling1D(),
        keras.layers.Dense(16, activation="relu"),
        keras.layers.Dense(4, activation="softmax"),
    ], name="cnn_cargo")

    model.compile(
        optimizer=keras.optimizers.Adam(1e-3),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )
    model.summary()

    cb = [
        keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True),
    ]
    history = model.fit(
        X_tr, y_tr,
        validation_data=(X_val_n, y_val),
        epochs=80, batch_size=256,
        callbacks=cb, verbose=1,
    )
    return model, history, norm


def cnn_to_tflite_int8(model, X_repr_raw, norm_fn, output_path):
    import tensorflow as tf

    X_repr_n = norm_fn(X_repr_raw)

    def representative_dataset():
        idx = np.random.default_rng(0).integers(0, len(X_repr_n), 200)
        for i in idx:
            yield [X_repr_n[i:i+1]]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type  = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model = converter.convert()
    with open(output_path, "wb") as f:
        f.write(tflite_model)
    size = len(tflite_model)
    print(f"  [CNN] TFLite int8 model: {output_path} ({size} bytes)")
    return tflite_model, size


# ────────────────────────────────────────────────────────────
# Evaluation helpers
# ────────────────────────────────────────────────────────────

def _print_cm(cm):
    print("         " + "  ".join(f"{c:>12}" for c in CLASS_NAMES))
    for i, row in enumerate(cm):
        print(f"  {CLASS_NAMES[i]:>8}  " + "  ".join(f"{v:>12d}" for v in row))


def evaluate_sklearn(model, X_test, y_test, name="RF"):
    from sklearn.metrics import classification_report, confusion_matrix
    y_pred = model.predict(X_test)
    report = classification_report(y_test, y_pred, target_names=CLASS_NAMES, digits=3)
    cm = confusion_matrix(y_test, y_pred)
    print(f"\n[{name}] Test classification report:")
    print(report)
    print(f"[{name}] Test confusion matrix:")
    _print_cm(cm)
    return report, cm, y_pred


def evaluate_tflite(tflite_model_bytes, X_test_input, y_test, name="TFLite"):
    """Run TFLite interpreter on test set and report accuracy."""
    try:
        import tensorflow as tf
        interp = tf.lite.Interpreter(model_content=tflite_model_bytes)
    except Exception:
        _require("tflite_runtime", "pip install tflite-runtime")
        from tflite_runtime.interpreter import Interpreter
        import tempfile, os
        with tempfile.NamedTemporaryFile(delete=False, suffix=".tflite") as tmp:
            tmp.write(tflite_model_bytes)
            tmp_path = tmp.name
        interp = Interpreter(model_path=tmp_path)
        os.unlink(tmp_path)

    interp.allocate_tensors()
    inp_det = interp.get_input_details()[0]
    out_det = interp.get_output_details()[0]
    inp_scale, inp_zero = inp_det["quantization"]
    out_scale, out_zero = out_det["quantization"]

    preds = []
    for i in range(len(X_test_input)):
        x = X_test_input[i:i+1]
        if inp_det["dtype"] == np.int8:
            if inp_scale > 0:
                x_q = np.round(x / inp_scale + inp_zero).clip(-128, 127).astype(np.int8)
            else:
                x_q = x.astype(np.int8)
        else:
            x_q = x.astype(inp_det["dtype"])
        interp.set_tensor(inp_det["index"], x_q)
        interp.invoke()
        out = interp.get_tensor(out_det["index"])[0]
        if out_det["dtype"] == np.int8:
            out = (out.astype(np.float32) - out_zero) * out_scale
        preds.append(int(np.argmax(out)))

    from sklearn.metrics import classification_report, confusion_matrix
    y_pred = np.array(preds)
    report = classification_report(y_test, y_pred, target_names=CLASS_NAMES, digits=3)
    cm = confusion_matrix(y_test, y_pred)
    print(f"\n[{name}] Test classification report (int8 quantised):")
    print(report)
    print(f"[{name}] Confusion matrix:")
    _print_cm(cm)
    return report, cm, y_pred


def tflite_to_c_header(tflite_bytes, var_name, output_path):
    """Convert a .tflite flat-buffer to a C header with a uint8 array."""
    lines = [
        "// Auto-generated by train_model.py — DO NOT EDIT",
        "#pragma once",
        "#include <stdint.h>",
        f"// Model size: {len(tflite_bytes)} bytes",
        f"const unsigned int {var_name}_len = {len(tflite_bytes)};",
        f"alignas(8) const unsigned char {var_name}[] = {{",
    ]
    hex_vals = [f"0x{b:02x}" for b in tflite_bytes]
    for i in range(0, len(hex_vals), 16):
        lines.append("  " + ", ".join(hex_vals[i:i+16]) + ",")
    lines += ["};"]
    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  C header written: {output_path}")


# ────────────────────────────────────────────────────────────
# Estimated arena size (heuristic, not measured on-device)
# ────────────────────────────────────────────────────────────

def estimate_arena_bytes_mlp():
    # MLP: Input(16) -> Dense(32) -> Dense(16) -> Dense(4)
    # Activations: 32 + 16 + 4 = 52 floats = 208 bytes (float32 or int8)
    # TFLite Micro overhead: ~2-4 KB typical for a model this size
    return 4 * 1024   # conservative estimate 4 KB

def estimate_arena_bytes_cnn():
    # CNN: (125,6) -> Conv1D(8,k=7,s=2)->(63,8) -> Conv1D(16,k=5,s=2)->(32,16)
    #   -> GAP -> Dense(16) -> Dense(4)
    # Largest activation tensor: 63*8=504 floats (int8: 504 bytes) plus Conv scratch
    # TFLite Micro overhead ~6-10 KB
    return 12 * 1024  # conservative estimate 12 KB


# ────────────────────────────────────────────────────────────
# Summary and selection
# ────────────────────────────────────────────────────────────

def select_and_report(results, output_dir):
    """
    Print a comparison table. Select winner based on:
    1. Must fit within MAX_MODEL_BYTES and MAX_ARENA_BYTES
    2. Highest test accuracy (macro F1)
    3. Tie-break: smallest model size
    """
    print("\n" + "="*70)
    print("MODEL COMPARISON (all on synthetic test set only)")
    print("="*70)
    print(f"  {'Model':12s}  {'Test Acc':>10}  {'Model KB':>10}  {'Arena KB':>10}  {'Fits?':>6}")
    print("-"*70)

    candidates = []
    for name, r in results.items():
        acc  = r.get("test_acc", 0.0)
        msz  = r.get("model_bytes", 0) / 1024
        asz  = r.get("arena_bytes", 0) / 1024
        fits = r.get("model_bytes", 0) <= MAX_MODEL_BYTES and \
               r.get("arena_bytes", 0) <= MAX_ARENA_BYTES
        print(f"  {name:12s}  {acc:>10.3f}  {msz:>10.1f}  {asz:>10.1f}  {'YES' if fits else 'NO':>6}")
        if fits:
            candidates.append((acc, -r.get("model_bytes", 0), name))

    if candidates:
        candidates.sort(reverse=True)
        winner = candidates[0][2]
        print(f"\n  >>> SELECTED: {winner} <<<")
        print("  (Best accuracy within ESP32 flash+arena budget)")
    else:
        print("\n  [!] No model fits within budget — check model sizes above.")
        winner = None

    print("="*70)
    report_path = Path(output_dir) / "comparison_report.json"
    with open(report_path, "w") as f:
        json.dump({"results": {k: {kk: vv for kk, vv in v.items()
                                    if isinstance(vv, (int, float, str, list))}
                               for k, v in results.items()},
                   "selected": winner}, f, indent=2)
    print(f"  Report saved: {report_path}")
    return winner


# ────────────────────────────────────────────────────────────
# Main
# ────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset",  default="dataset/")
    parser.add_argument("--output",   default="models/")
    parser.add_argument("--skip_cnn", action="store_true", help="Skip CNN training (saves time)")
    parser.add_argument("--skip_mlp", action="store_true", help="Skip MLP training")
    args = parser.parse_args()

    out = Path(args.output)
    out.mkdir(parents=True, exist_ok=True)

    print("Loading dataset and extracting features...")
    splits = load_features(args.dataset)
    Xf_tr, y_tr, X_tr_raw = splits["train"]
    Xf_val, y_val, X_val_raw = splits["val"]
    Xf_te, y_te, X_te_raw  = splits["test"]

    # Feature scaling (for RF and MLP)
    fmin, fmax = load_scaler_stats(Xf_tr)
    Xs_tr  = scale_features(Xf_tr, fmin, fmax)
    Xs_val = scale_features(Xf_val, fmin, fmax)
    Xs_te  = scale_features(Xf_te, fmin, fmax)
    np.save(out / "scaler_min.npy", fmin)
    np.save(out / "scaler_max.npy", fmax)

    results = {}

    # ── (a) Random Forest ──────────────────────────────────
    rf, rf_val_report, _ = train_random_forest(Xs_tr, y_tr, Xs_val, y_val)
    rf_report, rf_cm, rf_preds = evaluate_sklearn(rf, Xs_te, y_te, "RF")

    # Save joblib model for robustness_test.py and validate_real.py
    import joblib
    joblib.dump(rf, out / "model_rf.joblib")
    print(f"[RF] Saved scikit-learn model -> {out / 'model_rf.joblib'}")

    # Estimate model size: encode trees to C header and check file size
    rf_c_path = str(out / "model_rf.h")
    rf_size   = rf_to_c_code(rf, fmin, fmax, rf_c_path)
    # RF runs entirely on float features — no arena needed beyond feature buffer (16*4=64 bytes)
    rf_arena  = 256   # ~256 bytes for vote counters + stack

    from sklearn.metrics import accuracy_score
    rf_acc = accuracy_score(y_te, rf_preds)
    results["RF"] = {
        "test_acc": float(rf_acc),
        "model_bytes": rf_size,
        "arena_bytes": rf_arena,
        "report": rf_report,
    }

    # ── (b) MLP ────────────────────────────────────────────
    if not args.skip_mlp:
        mlp_model, _ = train_mlp(Xs_tr, y_tr.astype(np.int32),
                                  Xs_val, y_val.astype(np.int32))
        mlp_tflite_path = str(out / "model_mlp.tflite")
        mlp_tflite, mlp_size = mlp_to_tflite_int8(mlp_model, Xs_tr, mlp_tflite_path)

        # TFLite int8 evaluation
        mlp_report, mlp_cm, mlp_preds = evaluate_tflite(mlp_tflite, Xs_te, y_te, "MLP-int8")
        mlp_acc = accuracy_score(y_te, mlp_preds)

        # Write C header for firmware
        tflite_to_c_header(mlp_tflite, "g_mlp_model", str(out / "model_mlp_data.h"))

        results["MLP-int8"] = {
            "test_acc": float(mlp_acc),
            "model_bytes": mlp_size,
            "arena_bytes": estimate_arena_bytes_mlp(),
            "report": mlp_report,
        }
    else:
        print("[MLP] Skipped.")

    # ── (c) CNN ────────────────────────────────────────────
    if not args.skip_cnn:
        cnn_model, _, norm_fn = train_cnn(X_tr_raw, y_tr.astype(np.int32),
                                           X_val_raw, y_val.astype(np.int32))
        cnn_tflite_path = str(out / "model_cnn.tflite")
        cnn_tflite, cnn_size = cnn_to_tflite_int8(cnn_model, X_tr_raw, norm_fn, cnn_tflite_path)

        # TFLite int8 evaluation
        cnn_input = norm_fn(X_te_raw)
        cnn_report, cnn_cm, cnn_preds = evaluate_tflite(cnn_tflite, cnn_input, y_te, "CNN-int8")
        cnn_acc = accuracy_score(y_te, cnn_preds)

        tflite_to_c_header(cnn_tflite, "g_cnn_model", str(out / "model_cnn_data.h"))

        results["CNN-int8"] = {
            "test_acc": float(cnn_acc),
            "model_bytes": cnn_size,
            "arena_bytes": estimate_arena_bytes_cnn(),
            "report": cnn_report,
        }
    else:
        print("[CNN] Skipped.")

    winner = select_and_report(results, args.output)

    print("\nNOTE: All accuracy figures are on SYNTHETIC test data only.")
    print("Real-world accuracy is expected to be lower due to sim-to-real gap.")
    print("Use Phase 6 scripts to collect real data and re-evaluate.")


if __name__ == "__main__":
    main()
